name: llmstxt-social
region: lon1

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "15"
  - engine: REDIS
    name: redis
    num_nodes: 1
    size: db-s-dev-database
    version: "7"

services:
  - name: api
    dockerfile_path: packages/api/Dockerfile
    source_dir: /
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.DATABASE_URL}
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}

  - name: web
    dockerfile_path: Dockerfile
    source_dir: packages/web
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${APP_URL}/api
      - key: VITE_STRIPE_PUBLIC_KEY
        scope: BUILD_TIME
        type: SECRET

workers:
  - name: worker
    dockerfile_path: packages/api/Dockerfile
    source_dir: /
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: celery -A llmstxt_api.tasks.celery worker -l info
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.DATABASE_URL}
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CHARITY_COMMISSION_API_KEY
        scope: RUN_TIME
        type: SECRET
