"""Add dismissed_findings column

Revision ID: 7b64d535033a
Revises: 950f372e29cf
Create Date: 2026-01-17 12:17:45.720771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b64d535033a'
down_revision: Union[str, None] = '950f372e29cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('dismissed_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('monitoring_history', sa.Column('dismissed_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_history', 'dismissed_findings')
    op.drop_column('generation_jobs', 'dismissed_findings')
    # ### end Alembic commands ###
