"""Add sector and goal columns

Revision ID: 950f372e29cf
Revises: a1b2c3d4e5f6
Create Date: 2026-01-17 11:22:47.236478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950f372e29cf'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('sector', sa.String(length=50), nullable=True))
    op.add_column('generation_jobs', sa.Column('goal', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('sector', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('goal', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'goal')
    op.drop_column('subscriptions', 'sector')
    op.drop_column('generation_jobs', 'goal')
    op.drop_column('generation_jobs', 'sector')
    # ### end Alembic commands ###
