"""Add progress tracking fields

Revision ID: 9ef76566d8f1
Revises: 001
Create Date: 2026-01-15 12:01:25.667965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef76566d8f1'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('progress_stage', sa.String(length=50), nullable=True))
    op.add_column('generation_jobs', sa.Column('progress_detail', sa.String(length=255), nullable=True))
    op.add_column('generation_jobs', sa.Column('pages_crawled', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('total_pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'total_pages')
    op.drop_column('generation_jobs', 'pages_crawled')
    op.drop_column('generation_jobs', 'progress_detail')
    op.drop_column('generation_jobs', 'progress_stage')
    # ### end Alembic commands ###
